### ISSUE TITLE
Testing issue creation

### ISSUE THREAD

**Issue by mcgratta** [gforney/FDS-SMVgit#1]
I'm just testing how one creates an issue. I'm assigning it to Glenn. Add a few comments.

**Comment by gforney** [comment]
adding a comment to issue 1

On Tue, May 12, 2015 at 9:12 AM, mcgratta <notifications@github.com> wrote:

> I'm just testing how one creates an issue. I'm assigning it to Glenn. Add
> a few comments.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gforney/FDS-SMVgit/issues/1>.
>



-- 
Glenn Forney

**Comment by gforney** [comment]
this comment was added from the web page (the earlier comment was added by replying to the email I got)

**Comment by mcgratta** [comment]
I got an email and link to this page.

**Comment by mcgratta** [comment]
I accidentally closed the issue.

**Comment by gforney** [comment]
I'm going to close the issue also to see how to open it

**Comment by gforney** [comment]
simple - there is a reopen button!

**Comment by rmcdermo** [comment]
Just chiming in as a test.

**Comment by gforney** [comment]
welcome! have you been getting all the earlier emails about this issue also?

**Comment by rmcdermo** [comment]
Yes, but it is not clear to me how to check out the repository as a
developer.

**Comment by gforney** [comment]
I created the repository so was able to select who the collaborators are.
I added you, kevin and rick.  So you will be a developer when you check it
out.  I think anyone else checking it out will not be a developer ie will
not be able to make commmits (or perhaps they can make commits in their own
local repository but cannot push them to github).

It would be handy though to check out the repository as a normal user
(without commit privileges) I don't know how to do that.

On Tue, May 12, 2015 at 10:02 AM, Randy McDermott <notifications@github.com>
wrote:

> Yes, but it is not clear to me how to check out the repository as a
> developer.
>
>
> On Tue, May 12, 2015 at 9:57 AM, gforney <notifications@github.com> wrote:
>
> > welcome! have you been getting all the earlier emails about this issue
> > also?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/gforney/FDS-SMVgit/issues/1#issuecomment-101292407>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gforney/FDS-SMVgit/issues/1#issuecomment-101294241>.
>



-- 
Glenn Forney

**Comment by gforney** [comment]
so are we all going to get emails from all issues.  that could get to be annoying.

by the way, I only saw a button for making you all collaborators.  I didn't see how to make any of you owners.

**Comment by rmcdermo** [comment]
Closing issue.
